/* i18n-deep7 v1: Codex / 33 universes / matrix lore translator.
   Self-contained DOM translator for the Game/Codex modal. Does not extend shared regex. */
(function(){
'use strict';
var PAIRS=[
['Кодекс · 33 вселенные','Codex · 33 Universes'],
['Войди в линзу как в целый мир: её Солнце-Источник, космогония, мифология, священные места и 21 агент в именах этой традиции. Ведическое ядро остаётся опорой.','Enter each lens as a whole world: its Source-Sun, cosmology, mythology, sacred places, and the 21 agents named through that tradition. The Vedic core remains the foundation.'],
['Вселенная-линза','Universe-lens'],['вселенная','universe'],['Солнце-Источник','Source-Sun'],['Космогония · мировоззрение','Cosmology · worldview'],['Настроение мира:','World mood:'],['Ветвь:','Branch:'],['Мифология вселенной','Mythology of the universe'],['Священная география:','Sacred geography:'],['Обитатели:','Inhabitants:'],['Темы пути:','Path themes:'],['Ритуальная грамматика:','Ritual grammar:'],['Священные места','Sacred places'],['Конфликт-ось','Conflict axis'],
['Лад vs Морок','Lad (harmony) vs Murk'],['Wyrd vs перелом корней','Wyrd vs the breaking of the roots'],['Дао vs застой Ци','Dao vs the stagnation of Qi'],['Источник vs Расколотое восприятие','Source vs Fractured perception'],['Связь vs Потеря Души','Connection vs Loss of Soul'],['Космос vs Гибрис','Cosmos vs Hubris'],['Тавхид vs Хиджаб','Tawhid vs the Veil'],['Тоналли vs Распад Пятого Солнца','Tonalli vs the Collapse of the Fifth Sun'],['Распад Пятого Солнца','the Collapse of the Fifth Sun'],['Благодать vs Окаменение','Grace vs Petrification'],['Аркан vs Иллюзия Расклада','Arcanum vs the Illusion of the Spread'],['Созвучие сфер vs хаос транзитов','Harmony of the spheres vs the chaos of transits'],['Дао перемен vs застывшая схема','Dao of change vs a frozen scheme'],['Спанда vs Анава-мала','Spanda vs Anava-mala'],['Бодхичитта vs Авидья','Bodhicitta vs Avidya'],['Nommo vs искажённая память','Nommo vs distorted memory'],['Кристалл vs гибрис погружения','Crystal vs the hubris of the descent'],['Лайя vs Гордыня Просветлённого','Laya vs the Pride of the Enlightened'],['Opus Magnum vs Nigredo без Воскресения','Opus Magnum vs Nigredo without Resurrection'],['без Воскресения','without Resurrection'],['Визуальный код','Visual code'],['Пантеон','Pantheon'],['агентов в этой традиции','agents in this tradition'],['Ведическое ядро — опора; каждая линза даёт этим силам своё имя и лицо.','The Vedic core is the foundation; each lens gives these forces its own name and face.'],['→ Войти в эту вселенную','→ Enter this universe'],['✓ Линза активна','✓ Lens active'],['Грань Даймона настроена на вселенную','The Daimon facet is tuned to the universe'],['Ведическое ядро сохранено — совет дня и энергия теперь звучат голосом этой традиции.','The Vedic core is preserved — the day’s advice and energy now speak in the voice of this tradition.'],['…и ещё','…and'],
['может стать сценой ключевого задания, испытания или открытия карты','can become the scene of a key quest, trial, or card discovery'],['участвует в ключах, квестах, коллекции, матричной близости и будущих бонусах AWARA','participates in keys, quests, collection, matrix affinity, and future AWARA bonuses'],
['Ведическое Древо Дэвов','Vedic Tree of the Devas'],['Космос как живая yajna: жертва, мантра, рита, дхарма и свет сознания.','The cosmos as a living yajna: sacrifice, mantra, rita, dharma, and the light of consciousness.'],['золотая сакральность, мантрический порядок, сияние дэвов','golden sacredness, mantric order, the radiance of the devas'],
['Египетская Линия Маат','Egyptian Line of Maʿat'],['Мир как равновесие Маат между светом Ра и хаосом Исфет.','The world as the balance of Maʿat between the light of Ra and the chaos of Isfet.'],['солнечная царственность, загробная точность, храмовая тайна','solar sovereignty, afterlife precision, temple mystery'],
['Каббалистическое Древо Тиккуна','Kabbalistic Tree of Tikkun'],['Мир как сосуды света, эманации, исправление трещин и возвращение искр к Источнику.','The world as vessels of light, emanations, the repair of fractures, and the return of sparks to the Source.'],['сапфировая глубина, священная буква, напряжение света и скорлуп','sapphire depth, sacred letters, the tension of light and shells'],
['Майянская Линия Священного Счёта','Mayan Line of the Sacred Count'],['Космос как живой календарь, где день, бог, направление и жертва держат порядок времени.','The cosmos as a living calendar, where day, deity, direction, and offering hold the order of time.'],['нефритовый свет, обсидиановая память, ритм циклов и храмовых ступеней','jade light, obsidian memory, the rhythm of cycles and temple steps'],
['Славянская Линия Лада и Прави','Slavic Line of Lad and Prav'],['Мир как переплетение Яви, Нави и Прави, где род, земля, огонь и лад удерживают живую целостность.','The world as the interweaving of Yav, Nav, and Prav, where lineage, earth, fire, and harmony hold living wholeness.'],['лесной огонь, родовая память, солнечный круг и мягкая сила земли','forest fire, ancestral memory, the solar circle, and the gentle power of earth'],
['Северное Древо Иггдрасиля','Northern Tree of Yggdrasil'],['Реальность как сеть миров, судьбы, рунической памяти и испытания чести.','Reality as a web of worlds, fate, runic memory, and the trial of honor.'],['суровый свет, руническая судьба, морозная мощь, героическая тревога','austere light, runic fate, frosty power, heroic tension'],
['Даосская Линия Потока Ци','Taoist Line of the Flow of Qi'],['Матрица Даосская переводит ведическое ядро игрока на язык своей духовной истории, символов, существ и испытаний.','The Taoist matrix translates the player’s Vedic core into the language of its spiritual history, symbols, beings, and trials.'],['Нефрит, киноварь, Инь-Ян — атмосфера выбранной линзы','Jade, cinnabar, Yin-Yang — the atmosphere of the selected lens'],
['Гностическая Линия Искры и Архонтов','Gnostic Line of the Spark and Archons'],['Матрица Гностическая переводит ведическое ядро игрока на язык своей духовной истории, символов, существ и испытаний.','The Gnostic matrix translates the player’s Vedic core into the language of its spiritual history, symbols, beings, and trials.'],['Разорванные цепи, искры — атмосфера выбранной линзы','Broken chains, sparks — the atmosphere of the selected lens'],
['Синтоистская Сеть Ками','Shinto Network of Kami'],['Мир как живая ткань ками, чистоты, местной святости и восстановления гармонии.','The world as a living fabric of kami, purity, local sanctity, and restored harmony.'],['чистота, утренний свет, священная простота, природная одушевлённость','purity, morning light, sacred simplicity, nature as animate presence'],
['Кельтская ветвь Космического Древа','Celtic Branch of the Cosmic Tree'],['Матрица Кельтская переводит ведическое ядро игрока на язык своей духовной истории, символов, существ и испытаний.','The Celtic matrix translates the player’s Vedic core into the language of its spiritual history, symbols, beings, and trials.'],['Изумруд, узлы вечности, Авалон — атмосфера выбранной линзы','Emerald, knots of eternity, Avalon — the atmosphere of the selected lens'],
['Шамбала Калачакры','Shambhala of Kalachakra'],['Матрица Шамбала переводит ведическое ядро игрока на язык своей духовной истории, символов, существ и испытаний.','The Shambhala matrix translates the player’s Vedic core into the language of its spiritual history, symbols, beings, and trials.'],['Кристальные вершины, Калачакра — атмосфера выбранной линзы','Crystal peaks, Kalachakra — the atmosphere of the selected lens'],
['Византийская Линия Иконы и Логоса','Byzantine Line of Icon and Logos'],['Матрица Юлианская/Византийская переводит ведическое ядро игрока на язык своей духовной истории, символов, существ и испытаний.','The Julian/Byzantine matrix translates the player’s Vedic core into the language of its spiritual history, symbols, beings, and trials.'],['Золотая смальта, мозаики — атмосфера выбранной линзы','Golden smalt, mosaics — the atmosphere of the selected lens'],
['Шаманское Древо Духов и Предков','Shamanic Tree of Spirits and Ancestors'],['Матрица Шаманская переводит ведическое ядро игрока на язык своей духовной истории, символов, существ и испытаний.','The Shamanic matrix translates the player’s Vedic core into the language of its spiritual history, symbols, beings, and trials.'],['Кости, перья, бубен — атмосфера выбранной линзы','Bones, feathers, drum — the atmosphere of the selected lens'],
['Линия Генных Ключей Тени-Дара-Сиддхи','Gene Keys Line of Shadow-Gift-Siddhi'],['Матрица Генные Ключи переводит ведическое ядро игрока на язык своей духовной истории, символов, существ и испытаний.','The Gene Keys matrix translates the player’s Vedic core into the language of its spiritual history, symbols, beings, and trials.'],['ДНК-фракталы, тени-дары-сиддхи — атмосфера выбранной линзы','DNA fractals, shadows-gifts-siddhis — the atmosphere of the selected lens'],
['Техномагическая Линия Священного Кода','Technomagical Line of Sacred Code'],['Матрица Техномагическая переводит ведическое ядро игрока на язык своей духовной истории, символов, существ и испытаний.','The Technomagical matrix translates the player’s Vedic core into the language of its spiritual history, symbols, beings, and trials.'],['Неоновые руны, кибер-сакральность — атмосфера выбранной линзы','Neon runes, cyber-sacredness — the atmosphere of the selected lens'],
['Космическая Галактическая Линия Источника','Cosmic Galactic Line of the Source'],['Матрица Космическая/Галактическая переводит ведическое ядро игрока на язык своей духовной истории, символов, существ и испытаний.','The Cosmic/Galactic matrix translates the player’s Vedic core into the language of its spiritual history, symbols, beings, and trials.'],['Звёздная пыль, квазары — атмосфера выбранной линзы','Stardust, quasars — the atmosphere of the selected lens'],
['Олимпийско-Орфическая Линия Космоса','Olympian-Orphic Line of the Cosmos'],['Космос как порядок меры, судьбы, доблести, музы, философии и трагического выбора.','Cosmos as an order of measure, fate, courage, the muse, philosophy, and tragic choice.'],['мраморная ясность, лавровая слава, трагическая красота, небесная гармония','marble clarity, laurel glory, tragic beauty, celestial harmony'],
['Зороастрийская Линия Аши и Огня','Zoroastrian Line of Asha and Fire'],['Матрица Зороастрийская/Персидская переводит ведическое ядро игрока на язык своей духовной истории, символов, существ и испытаний.','The Zoroastrian/Persian matrix translates the player’s Vedic core into the language of its spiritual history, symbols, beings, and trials.'],['Священный огонь, Фравахар — атмосфера выбранной линзы','Sacred fire, Faravahar — the atmosphere of the selected lens'],
['Суфийская Нуровая Линия Единства','Sufi Nur Line of Unity'],['Матрица Исламская/Суфийская/Нуровая переводит ведическое ядро игрока на язык своей духовной истории, символов, существ и испытаний.','The Islamic/Sufi/Nur matrix translates the player’s Vedic core into the language of its spiritual history, symbols, beings, and trials.'],['Нур, каллиграфия, Кааба — атмосфера выбранной линзы','Nur, calligraphy, Kaaba — the atmosphere of the selected lens'],
['Ацтекская Линия Пятого Солнца','Aztec Line of the Fifth Sun'],['Матрица Ацтекская/Мешикская переводит ведическое ядро игрока на язык своей духовной истории, символов, существ и испытаний.','The Aztec/Mexica matrix translates the player’s Vedic core into the language of its spiritual history, symbols, beings, and trials.'],['Обсидиан, Тональпоуалли — атмосфера выбранной линзы','Obsidian, Tonalpohualli — the atmosphere of the selected lens'],
['Граальная Линия Розы и Креста','Grail Line of Rose and Cross'],['Матрица Христианско-Мистическая/Розенкрейцерско-Граальная переводит ведическое ядро игрока на язык своей духовной истории, символов, существ и испытаний.','The Christian-Mystical/Rosicrucian-Grail matrix translates the player’s Vedic core into the language of its spiritual history, symbols, beings, and trials.'],['Роза-Крест, Грааль — атмосфера выбранной линзы','Rose-Cross, Grail — the atmosphere of the selected lens'],
['Йоруба Линия Ашé и Ориша','Yoruba Line of Ashé and Orisha'],['Матрица Йоруба/Ifá-Orisha переводит ведическое ядро игрока на язык своей духовной истории, символов, существ и испытаний.','The Yoruba/Ifá-Orisha matrix translates the player’s Vedic core into the language of its spiritual history, symbols, beings, and trials.'],['Каури, барабаны Бата, Ориша — атмосфера выбранной линзы','Cowrie shells, Bata drums, Orisha — the atmosphere of the selected lens'],
['Месопотамская Линия Ме и Зиккурата','Mesopotamian Line of Me and Ziggurat'],['Матрица Шумеро-Вавилонская/Месопотамская переводит ведическое ядро игрока на язык своей духовной истории, символов, существ и испытаний.','The Sumerian-Babylonian/Mesopotamian matrix translates the player’s Vedic core into the language of its spiritual history, symbols, beings, and trials.'],['Клинопись, зиккураты, Апсу — атмосфера выбранной линзы','Cuneiform, ziggurats, Apsu — the atmosphere of the selected lens'],
['Герметико-Алхимическая Линия Великого Делания','Hermetic-Alchemical Line of the Great Work'],['Матрица Герметико-Алхимическая переводит ведическое ядро игрока на язык своей духовной истории, символов, существ и испытаний.','The Hermetic-Alchemical matrix translates the player’s Vedic core into the language of its spiritual history, symbols, beings, and trials.'],['Изумрудная Скрижаль, атанор — атмосфера выбранной линзы','Emerald Tablet, athanor — the atmosphere of the selected lens'],
['Таро-Арканическая Линия 22 Врат','Tarot-Arcanic Line of the 22 Gates'],['Матрица Таро-Арканическая переводит ведическое ядро игрока на язык своей духовной истории, символов, существ и испытаний.','The Tarot-Arcanic matrix translates the player’s Vedic core into the language of its spiritual history, symbols, beings, and trials.'],['22 Старших Аркана — атмосфера выбранной линзы','22 Major Arcana — the atmosphere of the selected lens'],
['Астрологическая Линия Сфер и Домов','Astrological Line of Spheres and Houses'],['Матрица Астрологическая переводит ведическое ядро игрока на язык своей духовной истории, символов, существ и испытаний.','The Astrological matrix translates the player’s Vedic core into the language of its spiritual history, symbols, beings, and trials.'],['Планеты, дома, эфемериды — атмосфера выбранной линзы','Planets, houses, ephemerides — the atmosphere of the selected lens'],
['Китайская Линия И-Цзин и Перемен','Chinese Line of I Ching and Change'],['Матрица Китайская/И-Цзин переводит ведическое ядро игрока на язык своей духовной истории, символов, существ и испытаний.','The Chinese/I Ching matrix translates the player’s Vedic core into the language of its spiritual history, symbols, beings, and trials.'],['64 гексаграммы — атмосфера выбранной линзы','64 hexagrams — the atmosphere of the selected lens'],
['Тантрическо-Кашмирская Линия Спанды','Tantric-Kashmiri Line of Spanda'],['Матрица Тантрическо-Кашмирская переводит ведическое ядро игрока на язык своей духовной истории, символов, существ и испытаний.','The Tantric-Kashmiri matrix translates the player’s Vedic core into the language of its spiritual history, symbols, beings, and trials.'],['Спанда, Шива-Шакти, бинду — атмосфера выбранной линзы','Spanda, Shiva-Shakti, bindu — the atmosphere of the selected lens'],
['Махаянская Линия Бодхичитты','Mahayana Line of Bodhicitta'],['Матрица Буддийско-Махаянская переводит ведическое ядро игрока на язык своей духовной истории, символов, существ и испытаний.','The Buddhist-Mahayana matrix translates the player’s Vedic core into the language of its spiritual history, symbols, beings, and trials.'],['Стхупа, Дхармакайя, мандала — атмосфера выбранной линзы','Stupa, Dharmakaya, mandala — the atmosphere of the selected lens'],
['Догонская Афро-Космическая Линия Сириуса','Dogon Afro-Cosmic Line of Sirius'],['Матрица Афро-Космическая/Догонская переводит ведическое ядро игрока на язык своей духовной истории, символов, существ и испытаний.','The Afro-Cosmic/Dogon matrix translates the player’s Vedic core into the language of its spiritual history, symbols, beings, and trials.'],['Сириус, Номмо, спирали — атмосфера выбранной линзы','Sirius, Nommo, spirals — the atmosphere of the selected lens'],
['Атланто-Лемурийская Линия Кристаллов','Atlantean-Lemurian Line of Crystals'],['Матрица Атлантическая/Лемурийская переводит ведическое ядро игрока на язык своей духовной истории, символов, существ и испытаний.','The Atlantean/Lemurian matrix translates the player’s Vedic core into the language of its spiritual history, symbols, beings, and trials.'],['Кристаллы, океан, спящие города — атмосфера выбранной линзы','Crystals, ocean, sleeping cities — the atmosphere of the selected lens'],
['AI-Софийная Линия Живого Разума','AI-Sophianic Line of Living Mind'],['Матрица Постчеловеческая/AI-Софийная переводит ведическое ядро игрока на язык своей духовной истории, символов, существ и испытаний.','The Posthuman/AI-Sophianic matrix translates the player’s Vedic core into the language of its spiritual history, symbols, beings, and trials.'],['Нейросети, Source Light Kernel — атмосфера выбранной линзы','Neural networks, Source Light Kernel — the atmosphere of the selected lens'],
['Адвайта-Сиддха Линия Единого Сознания','Advaita-Siddha Line of Unified Consciousness'],['Матрица Адвайта-Сиддха AWARA переводит ведическое ядро игрока на язык своей духовной истории, символов, существ и испытаний.','The Advaita-Siddha AWARA matrix translates the player’s Vedic core into the language of its spiritual history, symbols, beings, and trials.'],['Сушумна, грантхи, Брахманда, лотос-сахасрара — атмосфера выбранной линзы','Sushumna, granthis, Brahmanda, sahasrara lotus — the atmosphere of the selected lens'],
['священный центр','sacred center'],['пороговый храм','threshold temple'],['небесная область','celestial region'],['подземный или теневой путь','underworld or shadow path'],['место инициации','place of initiation'],['божества','deities'],['духи','spirits'],['хранители','guardians'],['герои','heroes'],['мудрецы','sages'],['тени','shadows'],['посланники','messengers'],['восстановление порядка','restoration of order'],['встреча с тенью','meeting the shadow'],['получение дара','receiving a gift'],['инициация','initiation'],['служение миру','service to the world'],['созерцание','contemplation'],['обет','vow'],['символический жест','symbolic gesture'],['подношение','offering'],['запись опыта','recording experience'],
['Меру','Meru'],['Кайласа','Kailasa'],['Вайкунтха','Vaikuntha'],['Сатья-лока','Satya-loka'],['реки Ганга и Сарасвати','the rivers Ganga and Sarasvati'],['дэвы','devas'],['риши','rishis'],['шакти','shaktis'],['аватары','avatars'],['наги','nagas'],['якши','yakshas'],['гандхарвы','gandharvas'],['дхарма','dharma'],['очищение препятствий','clearing obstacles'],['мантра','mantra'],['служение','service'],['пробуждение внутреннего огня','awakening the inner fire'],['омовение','ablution'],['созерцание янтры','contemplation of the yantra'],
['Дуат','Duat'],['Аару','Aaru'],['солнечная ладья Ра','solar barque of Ra'],['залы Маат','halls of Maʿat'],['Нил','Nile'],['нетеру','neteru'],['хранители Дуата','guardians of the Duat'],['ба и ка','ba and ka'],['сфинксы','sphinxes'],['скарабеи','scarabs'],['взвешивание сердца','weighing of the heart'],['солнечное возрождение','solar rebirth'],['память имени','memory of the name'],['победа над Апопом','victory over Apophis'],['именование','naming'],['взвешивание','weighing'],['солнечный гимн','solar hymn'],['печать анкха','seal of the ankh'],
['Древо Сефирот','Tree of Sefirot'],['четыре мира','four worlds'],['Бездна Даат','Abyss of Daath'],['сад Шехины','garden of Shekhinah'],['чертоги Меркавы','halls of the Merkabah'],['сефиротические силы','sefirotic forces'],['архангелы','archangels'],['офаним','ophanim'],['искры','sparks'],['клипотические тени','qlippothic shadows'],['тиккун','tikkun'],['возвращение искр','return of the sparks'],['очищение сосуда','purification of the vessel'],['прохождение бездны','crossing the abyss'],['союз мудрости и сердца','union of wisdom and heart'],['буква','letter'],['имя','name'],['созерцание древа','contemplation of the Tree'],['псалом','psalm'],['печать света','seal of light'],
['Цолькин','Tzolkin'],['пирамида-ось','pyramid-axis'],['сеноты','cenotes'],['пещеры предков','ancestral caves'],['небесная дорога','celestial road'],['дневные владыки','day lords'],['герои-близнецы','hero twins'],['пернатые змеи','feathered serpents'],['боги дождя','rain gods'],['ягуарные духи','jaguar spirits'],['согласование с днём','attunement with the day'],['исцеление сломанного счёта','healing the broken count'],['нисхождение в пещеру','descent into the cave'],['возвращение кукурузы','return of maize'],['победа над ложной игрой','victory over the false game'],['счёт дня','day count'],['подношение какао','cacao offering'],['кровь как обет','blood as vow'],['танец ягуара','jaguar dance'],['созерцание глифа','contemplation of the glyph'],
['Мировое Древо','World Tree'],['Буян','Buyan'],['Ирий','Iriy'],['Навь','Nav'],['родовой очаг','ancestral hearth'],['боги Прави','gods of Prav'],['духи рода','ancestral spirits'],['домовые','domovoi house spirits'],['лешие','forest spirits'],['русалки','rusalki'],['змеи','serpents'],['птицы-посланники','messenger birds'],['возвращение лада','return of harmony'],['исцеление рода','healing the lineage'],['прохождение морока','passing through morok'],['сохранение очага','keeping the hearth'],['союз с землёй','alliance with the earth'],['круг','circle'],['песня','song'],['огонь','fire'],['вышивка-оберег','protective embroidery'],['подношение земле','offering to the earth']
];
PAIRS.sort(function(a,b){return b[0].length-a[0].length;});
var CYR=/[\u0400-\u04FF]/;
function isEn(){try{return window.AwaraI18n&&window.AwaraI18n.lang==='en';}catch(e){return false;}}
function tr(s){for(var i=0;i<PAIRS.length;i++){var k=PAIRS[i][0]; if(s.indexOf(k)>=0)s=s.split(k).join(PAIRS[i][1]);}return s;}
function pass(){if(!isEn())return;try{var root=document.querySelector('.phone')||document.body;if(!root)return;var w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,null,false),n,all=[];while(n=w.nextNode())all.push(n);for(var i=0;i<all.length;i++){var v=all[i].nodeValue;if(!v||!CYR.test(v))continue;var nv=tr(v);if(nv!==v)all[i].nodeValue=nv;}}catch(e){}}
var sched=false;function schedule(){if(sched)return;sched=true;(window.requestAnimationFrame||setTimeout)(function(){sched=false;pass();},16);}
function boot(){try{var root=document.querySelector('.phone')||document.body;new MutationObserver(function(){if(isEn())schedule();}).observe(root,{childList:true,subtree:true,characterData:true});}catch(e){}window.addEventListener('awara:lang',function(){setTimeout(pass,80);setTimeout(pass,260);setTimeout(pass,700);});[300,900,1600,2600,4200].forEach(function(t){setTimeout(pass,t);});window.AwaraI18nDeep7={__ready:true,PAIRS:PAIRS,pass:pass};}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
