/* AWARA · i18n-deep — перевод динамически отрисованного русского текста (натал, агенты, покровитель, формы Даймона, системы расчёта, HD) на EN.
   Работает поверх i18n.js: словарь целых фраз + атомов, замена в текстовых узлах экранов, реакция на смену языка и перерисовку. */
(function(){
'use strict';
if(window.AwaraI18nDeep&&window.AwaraI18nDeep.__ready)return;

var T={
/* --- планеты (+ склонения) --- */
'Лагной':'Lagna','Лагны':'Lagna','Лагна':'Lagna','Солнцем':'Sun','Солнца':'Sun','Солнце':'Sun','Луной':'Moon','Луны':'Moon','Луна':'Moon','Меркурий':'Mercury','Венера':'Venus','Марс':'Mars','Юпитер':'Jupiter','Сатурн':'Saturn','Раху':'Rahu','Кету':'Ketu','Уран':'Uranus','Нептун':'Neptune','Плутон':'Pluto','Сев.Узел':'N.Node','Юж.Узел':'S.Node',
/* --- знаки --- */
'Овен':'Aries','Телец':'Taurus','Близнецы':'Gemini','Рак':'Cancer','Лев':'Leo','Дева':'Virgo','Весы':'Libra','Скорпион':'Scorpio','Стрелец':'Sagittarius','Козерог':'Capricorn','Водолей':'Aquarius','Рыбы':'Pisces',
/* --- стихии --- */
'Огонь':'Fire','Воздух':'Air','Вода':'Water','Эфир':'Ether','Гроза':'Storm','Рассвет':'Dawn','Земля':'Earth',
'огонь':'fire','воздух':'air','вода':'water','эфир':'ether','гроза':'storm','земля':'earth',
/* --- накшатры --- */
'Ашвини':'Ashwini','Бхарани':'Bharani','Криттика':'Krittika','Рохини':'Rohini','Мригашира':'Mrigashira','Ардра':'Ardra','Пунарвасу':'Punarvasu','Пушья':'Pushya','Ашлеша':'Ashlesha','Магха':'Magha','Пурва-Пхальгуни':'Purva Phalguni','Уттара-Пхальгуни':'Uttara Phalguni','Хаста':'Hasta','Читра':'Chitra','Свати':'Swati','Вишакха':'Vishakha','Анурадха':'Anuradha','Джьештха':'Jyeshtha','Мула':'Mula','Пурва-Ашадха':'Purva Ashadha','Уттара-Ашадха':'Uttara Ashadha','Шравана':'Shravana','Дхаништха':'Dhanishta','Шатабхиша':'Shatabhisha','Пурва-Бхадрапада':'Purva Bhadrapada','Уттара-Бхадрапада':'Uttara Bhadrapada','Ревати':'Revati',
/* --- гуны / доши --- */
'Раджас':'Rajas','Саттва':'Sattva','Тамас':'Tamas','Капха-Вата':'Kapha-Vata','Питта':'Pitta','Капха':'Kapha','Вата':'Vata',
/* --- стороны света --- */
'Северо-запад':'Northwest','Северо-восток':'Northeast','Юго-восток':'Southeast','Юго-запад':'Southwest','Восток':'East','Запад':'West','Север':'North','Юг':'South','Центр':'Center',
/* === inline renderNatal (подпись карты) === */
'Лагна в ':'Lagna in ',', Луна в ':', Moon in ','Акцент — ':'Accent — ',' планеты).':' planets).','Планеты распределены широко.':'Planets are widely distributed.',' Аянамша ≈':' Ayanamsha ≈','Подпись карты':'Chart signature','Карта (сидерическая)':'Chart (sidereal)','Натальная карта':'Natal chart','Рассчитать карту':'Calculate chart','Основа · расчёт из даты':'Basis · calculation from date',
/* === inline renderDaimon === */
'Твой Даймон · из наталки':'Your Daimon · from the chart','Арка речи':'Speech arc','Натальная основа':'Natal foundation','Имена по матрицам':'Names across matrices','Накшатра Луны':'Moon nakshatra','Управитель':'Ruler','Архетип':'Archetype','Шёпот':'Whisper','Голос':'Voice','Молчание':'Silence','Доверие ':'Trust ',' · режим ':' · mode ','Ведическая':'Vedic','Герметизм':'Hermetic','Славянская':'Slavic','Техномагия':'Technomagic',', рождён из ':', born of ','. Пока ты плавишь дни, я говорю твоим ':'. While you melt your days, I speak with your ',
/* === daimon-forms === */
'Формы Даймона · из натальной карты':'Daimon forms · from the natal chart','Качества из карты':'Qualities from the chart','Акцент стихии':'Element accent','Доша Лагны':'Lagna dosha','Гуна':'Guna','Первозданный':'Primordial','Лик · ':'Face · ','Солнечный · ':'Solar · ','Страж · ':'Guardian · ','Воитель':'Warrior','Хранитель':'Keeper','Вестник':'Herald','Страж очага':'Hearth Guardian','Венценосец':'Crowned One','Зодчий':'Architect','Гармонизатор':'Harmonizer','Преобразитель':'Transformer','Странник':'Wanderer','Восходящий':'Ascendant','Провидец':'Seer','Мистик':'Mystic','Спутник':'Companion','Пламенный':'Fiery','Незыблемый':'Unshakable','Ветреный':'Airy','Уравновешенный':'Balanced',
'Первозданная форма — из накшатры Луны ':'Primordial form — from the Moon nakshatra ',' (стихия ':' (element ','). Голос древний и мощный.':'). Ancient and mighty voice.','Лик — проявленная форма от Лагны в ':'Face — manifested form from Lagna in ','). Архетип: ':'). Archetype: ','Солнечная форма — от Солнца в ':'Solar form — from the Sun in ','). Воля и сияние.':'). Will and radiance.','Доминанта карты — стихия ':'Chart dominant — element ',' из 8 точек). Форма-страж.':' of 8 points). Guardian form.','Темперамент по доше Лагны: ':'Temperament by Lagna dosha: ',
'«Я — ':'«I am ',', зверь, рождённый из ':', a beast born of ','. Под бурей я истинен.»':'. In the storm I am true.»','«В облике Лика я — ':'«In the Face form I am ',', мягкий голос Лагны в ':', the soft voice of Lagna in ','«Я — солнечный ':'«I am the solar ',' твоего Солнца в ':' of your Sun in ','. Со мной ты сияешь волей.»':'. With me you shine with will.»','«Я — Страж стихии ':'«I am the Guardian of the element ',', той, что правит твоей картой.»':', the one that rules your chart.»','«Мой нрав — ':'«My temper is ','. Я отражаю твой телесный огонь и ритм.»':'. I reflect your bodily fire and rhythm.»','Форма: ':'Form: ',
/* === 21 агент: имена === */
'Сурья':'Surya','Сома (Чандра)':'Soma (Chandra)','Сканда (Мангала)':'Skanda (Mangala)','Будха':'Budha','Брихаспати (Гуру)':'Brihaspati (Guru)','Шукра':'Shukra','Шани':'Shani','Шакти':'Shakti','Сарасвати':'Saraswati','Лакшми':'Lakshmi','Вишну':'Vishnu','Шива':'Shiva','Агни (Искра)':'Agni (Spark)','Ваю':'Vayu','Варуна':'Varuna','Индра':'Indra','Притхви':'Prithvi','Яма':'Yama','Шанти':'Shanti',
/* агент: домены */
'Воля, душа, достоинство':'Will, soul, dignity','Ум, чувства, забота':'Mind, feelings, care','Отвага, действие, защита':'Courage, action, protection','Разум, речь, обмен':'Mind, speech, exchange','Мудрость, вера, рост':'Wisdom, faith, growth','Любовь, красота, вкус':'Love, beauty, taste','Дисциплина, труд, время':'Discipline, work, time','Желание, прорыв, новизна':'Desire, breakthrough, novelty','Освобождение, интуиция, мокша':'Liberation, intuition, moksha','Сила, движение, воля':'Power, motion, will','Знание, искусство, речь':'Knowledge, art, speech','Изобилие, удача, поток':'Abundance, fortune, flow','Хранение, гармония, дхарма':'Preservation, harmony, dharma','Преображение, аскеза, покой':'Transformation, asceticism, peace','Огонь, ритм, преображение':'Fire, rhythm, transformation','Дыхание, свобода, движение':'Breath, freedom, movement','Воды, чувства, очищение':'Waters, feelings, cleansing','Победа, лидерство, воля':'Victory, leadership, will','Земля, опора, тело':'Earth, support, body','Границы, честность, долг':'Boundaries, honesty, duty','Покой, тишина, исцеление':'Peace, silence, healing',
/* агент: учения */
'Свет Ра в сердце — твоя суть не нуждается в одобрении, она сияет сама.':'The Light of Ra in the heart — your essence needs no approval, it shines on its own.','Луна хранит воды ума — каков сосуд, такова и тишина внутри.':'The Moon holds the waters of the mind — as is the vessel, so is the stillness within.','Копьё Сканды бьёт раз — но точно. Сила не в ярости, а в направлении.':'The spear of Skanda strikes once — but truly. Strength is not in rage but in direction.','Слово — мост. Будха учит говорить так, чтобы соединять, а не делить.':'A word is a bridge. Budha teaches to speak so as to unite, not divide.','Гуру расширяет: где есть смысл, там и путь.':'The Guru expands: where there is meaning, there is the path.','Шукра знает: наслаждение свято, когда оно осознанно.':'Shukra knows: pleasure is sacred when it is conscious.','Шани не наказывает — он выпрямляет. Терпение есть форма любви ко времени.':'Shani does not punish — he straightens. Patience is a form of love for time.','Раху голоден до небывалого — он ведёт за грань привычного.':'Rahu hungers for the unprecedented — he leads beyond the familiar.','Кету отрезает лишнее — то, что отпало, и было оковами.':'Ketu cuts away the excess — what fell away was the chains.','Шакти — энергия, что течёт сквозь намерение в дело.':'Shakti is the energy that flows through intention into action.','Сарасвати течёт рекой — знание живо, лишь когда движется.':'Saraswati flows like a river — knowledge is alive only when it moves.','Лакшми приходит к чистому и открытому — изобилие любит порядок.':'Lakshmi comes to the clean and open — abundance loves order.','Вишну держит мир — поддерживая, а не сжимая.':'Vishnu holds the world — by supporting, not by gripping.','Шива танцует разрушение, чтобы родилось новое; в центре танца — тишина.':'Shiva dances destruction so the new may be born; at the center of the dance — stillness.','Агни принимает любое подношение и обращает в свет.':'Agni accepts any offering and turns it into light.','Ваю незрим, но движет всем — дыхание есть нить жизни.':'Vayu is unseen yet moves all — breath is the thread of life.','Варуна хранит закон вод — чувства чисты, когда текут, а не застаиваются.':'Varuna keeps the law of waters — feelings are pure when they flow, not stagnate.','Индра побеждает засуху Вритры — преграда падает перед собранной волей.':'Indra defeats the drought of Vritra — the obstacle falls before gathered will.','Притхви держит всё — щедро и молча. Опора рождается из устойчивости.':'Prithvi holds everything — generously and silently. Support is born of steadiness.','Яма — владыка меры; честность с собой избавляет от страха конца.':'Yama is the lord of measure; honesty with yourself frees you from the fear of the end.','Шанти — не отсутствие бури, а центр, что не качается в буре.':'Shanti is not the absence of storm, but the center that does not sway in it.',
/* агент: советы */
'Сделай сегодня одно дело от лица своей подлинной воли, не спрашивая разрешения.':'Do one thing today from your true will, without asking permission.','Позаботься о ком-то и о себе одинаково нежно; напои ум покоем.':'Care for someone and for yourself with equal tenderness; give the mind peace.','Выбери один страх и сделай к нему один смелый шаг.':'Choose one fear and take one brave step toward it.','Скажи или напиши одну ясную, честную мысль тому, кому она нужна.':'Say or write one clear, honest thought to someone who needs it.','Удели час тому, что растит тебя — учению, наставнику или ученику.':'Give an hour to what grows you — study, a mentor, or a student.','Создай или раздели сегодня что-то красивое — без вины, с благодарностью.':'Create or share something beautiful today — without guilt, with gratitude.','Доведи до конца одно скучное, но важное дело. В этом твоя свобода.':'Finish one boring but important task. Therein lies your freedom.','Сделай шаг в незнакомое; отличи истинное желание от наваждения.':'Step into the unknown; tell true desire from delusion.','Откажись сегодня от одной привязанности и побудь в тишине.':'Let go of one attachment today and rest in silence.','Преврати одно намерение в конкретное действие прямо сейчас.':'Turn one intention into a concrete action right now.','Запиши, нарисуй или сыграй то, что узнал. Дай знанию форму.':'Write, draw, or play what you learned. Give knowledge a form.','Наведи порядок в одном месте и поблагодари за то, что уже есть.':'Tidy one place and give thanks for what you already have.','Поддержи то, что хрупко и ценно, но не вмешивайся сверх меры.':'Support what is fragile and precious, but do not overreach.','Отпусти одну старую форму себя и посиди в безмолвии 10 минут.':'Let go of one old form of yourself and sit in silence for 10 minutes.','Зажги ритм дня: одно действие в одно и то же время — и держи искру.':'Light the rhythm of the day: one action at the same time — and keep the spark.','Сделай 20 осознанных дыханий и впусти свежесть в застывшее.':'Take 20 conscious breaths and let freshness into the stagnant.','Назови честно одно чувство и дай ему пройти, как воде.':'Honestly name one feeling and let it pass, like water.','Возьми ответственность за одно дело как лидер и доведи его до победы.':'Take charge of one task as a leader and carry it to victory.','Сделай одно дело для тела и дома: еда, порядок, прогулка по земле.':'Do one thing for body and home: food, order, a walk on the earth.','Скажи честное «нет» одному лишнему и сдержи одно данное слово.':'Say an honest «no» to one excess and keep one given word.','Подари себе 15 минут полной тишины без экранов и задач.':'Give yourself 15 minutes of full silence, free of screens and tasks.',
/* граха-резонанс */
'воля и душа':'will and soul','ум и чувства':'mind and feelings','действие и отвага':'action and courage','разум и слово':'mind and word','мудрость и рост':'wisdom and growth','любовь и изобилие':'love and abundance','дисциплина и время':'discipline and time','прорыв и желание':'breakthrough and desire','освобождение и интуиция':'liberation and intuition',
/* агент: подписи/покровитель */
'Покровитель дня · по текущей даше':'Patron of the day · by current dasha','Покровитель дня':'Patron of the day','Рассчитай натальную карту на экране «Натал» — и проявится покровитель текущего периода.':'Calculate your natal chart on the Natal screen — and the patron of the current period will appear.','ведёт Маха-дашу ':'leads the Mahadasha ','Со-покровитель · Антар-даша ':'Co-patron · Antardasha ','Сфера и направление':'Sphere and direction',' · мандала Васту: ':' · Vastu mandala: ','Граха-резонанс':'Graha resonance','Совет покровителя':'Patron advice','✦ Сейчас твой покровитель':'✦ Now your patron','Идёт Маха-даша ':'The Mahadasha ',' — этот агент ведёт твой период. Его сфера сейчас особенно живая.':' is active — this agent leads your period. Its sphere is especially alive now.','◆ Со-покровитель периода':'◆ Co-patron of the period','Идёт Антар-даша ':'The Antardasha ',' — этот агент оттеняет нынешний путь.':' is active — this agent shades the current path.','21 агент · мандала Васту':'21 agents · Vastu mandala','Каждый агент — сила одной сферы жизни. Нажми, чтобы услышать его наставление.':'Each agent is the power of one sphere of life. Tap to hear its teaching.',
/* === advice-energy === */
'Покровитель дня — ':'Patron of the day — ',', Маха-даша ':', Mahadasha ','Твой день звучит в ладу с ':'Your day resonates in harmony with ','твоей глубинной природе':'your deep nature','Луной в ':'the Moon in ','Энергии линз (+':'Lens energies (+',' Света): ':' Light): ',', созвучна стихии ':', attuned to the element ','Выбери линзы в Тигле — и совет станет глубже. ':'Choose lenses in the Crucible — and the advice will deepen. ','Выбери линзы в Тигле — и совет станет глубже.':'Choose lenses in the Crucible — and the advice will deepen.','Ты написал: «':'You wrote: «','» — это уже первый шаг алхимии.':'» — this is already the first step of alchemy.','База ':'Base ',' · намерения +':' · intentions +',' · энергии линз +':' · lens energies +',' · линзы +':' · lenses +',' (✦':' (✦',' созвучных)':' attuned)',' · Даймон +':' · Daimon +',
/* энергии 33 линз */
'Дхармическая ось':'Dharmic axis','Сила архетипа':'Archetype power','Нисхождение света':'Descent of light','Алхимия соответствий':'Alchemy of correspondences','Сила Рода':'Power of the Kin','Искра пробуждения':'Spark of awakening','Поток у-вэй':'Wu-wei flow','Энергия перемен':'Energy of change','Путь Ра':'Path of Ra','Ритм Цолькин':'Tzolkin rhythm','Жар жертвы':'Heat of sacrifice','Корни дерева':'Tree roots','Сила руны':'Rune power','Зов духов':'Call of spirits','Освобождение от жажды':'Release from craving','Пламя любви':'Flame of love','Чаша служения':'Cup of service','Кристалл памяти':'Crystal of memory','Воин света':'Warrior of light','Тень → дар':'Shadow → gift','Игра планет':'Play of planets','Галактический луч':'Galactic ray','Чистота ками':'Purity of kami','Закон Ме':'Law of Me','Выбор света':'Choice of light','Ритм предков':'Rhythm of ancestors','Аше Ориша':'Ashe of Orisha','Спанда Шивы':'Spanda of Shiva','Софийный синтез':'Sophian synthesis','Код-заклинание':'Spell-code','Недвойственность':'Non-duality','Умное безмолвие':'Noetic silence','Песнь нисхождения':'Song of descent',
/* === natal-deep === */
'🔭 Положения · дома · дигнитет':'🔭 Positions · houses · dignity','Дом ':'House ','Экзальтация ↑':'Exaltation ↑','Падение ↓':'Debilitation ↓','Своя обитель':'Own sign','🧬 Аспекты (дришти)':'🧬 Aspects (drishti)','Соединения:':'Conjunctions:','смотрит на: ':'aspects: ','Нет взаимных аспектов между занятыми знаками.':'No mutual aspects between occupied signs.','⛜ Йоги (сочетания)':'⛜ Yogas (combinations)','Особых классических йог не выявлено.':'No notable classical yogas detected.','🌀 Вимшоттари Даша · сейчас':'🌀 Vimshottari Dasha · now','Маха-даша ':'Mahadasha ','Антар-даша ':'Antardasha ','пройдено ':'elapsed ',' · осталось ':' · remaining ','осталось ':'remaining ','Дальше: ':'Next: ','📜 Панчанга рождения':'📜 Birth Panchanga','Вара (день)':'Vara (weekday)','Титхи':'Tithi','Нитья-йога':'Nitya Yoga','Шукла (растущая)':'Shukla (waxing)','Кришна (убывающая)':'Krishna (waning)','✦ Акценты карты':'✦ Chart accents','Экзальтация: ':'Exaltation: ','Падение: ':'Debilitation: ','Акцент — Дом ':'Accent — House ',' г ':' y ',' мес':' mo',
/* дни недели */
'Воскресенье':'Sunday','Понедельник':'Monday','Вторник':'Tuesday','Среда':'Wednesday','Четверг':'Thursday','Пятница':'Friday','Суббота':'Saturday',
/* нитья-йоги */
'Вишкамбха':'Vishkambha','Прити':'Priti','Аюшман':'Ayushman','Саубхагья':'Saubhagya','Шобхана':'Shobhana','Атиганда':'Atiganda','Сукарма':'Sukarma','Дхрити':'Dhriti','Шула':'Shula','Ганда':'Ganda','Вриддхи':'Vriddhi','Дхрува':'Dhruva','Вьягхата':'Vyaghata','Харшана':'Harshana','Ваджра':'Vajra','Сиддхи':'Siddhi','Вьятипата':'Vyatipata','Вариян':'Variyan','Паригха':'Parigha','Сиддха':'Siddha','Садхья':'Sadhya','Шубха':'Shubha','Шукла':'Shukla','Брахма':'Brahma','Вайдхрити':'Vaidhriti',
/* йоги-сочетания */
'Гаджакесари':'Gajakesari','Юпитер в кендре от Луны — мудрость, уважение, благополучие.':'Jupiter in a kendra from the Moon — wisdom, respect, well-being.','Будха-Адитья':'Budha-Aditya','Солнце и Меркурий вместе — острый ум, интеллект, речь.':'Sun and Mercury together — sharp mind, intellect, speech.','Чандра-Мангала':'Chandra-Mangala','Луна и Марс вместе — энергия, предприимчивость, добыча средств.':'Moon and Mars together — energy, enterprise, gaining of means.','Ручака':'Ruchaka','Бхадра':'Bhadra','Хамса':'Hamsa','Малавья':'Malavya','Шаша':'Shasha',' (Маха-пуруша)':' (Maha-purusha)',' силён в кендре — выдающееся качество личности.':' is strong in a kendra — an outstanding quality of personality.','Кала-Сарпа':'Kala-Sarpa','Все планеты по одну сторону оси Раху-Кету — интенсивная судьба, рывками.':'All planets on one side of the Rahu-Ketu axis — an intense destiny, in surges.','Кемадрума':'Kemadruma','Луна без поддержки соседних планет — урок опоры на себя.':'Moon without support from neighboring planets — a lesson in self-reliance.','Раджа-йога':'Raja Yoga','Соединение управителей кендры и тригоны (':'Union of kendra and trikona lords (',') — рост статуса и власти.':') — rise in status and power.','Дхана-йога':'Dhana Yoga','Управители 2 и 11 домов вместе (':'Lords of the 2nd and 11th houses together (',') — потенциал накопления богатства.':') — potential to accumulate wealth.',
/* бхавы (акценты) */
'Личность, тело, витальность':'Self, body, vitality','Богатство, речь, семья':'Wealth, speech, family','Смелость, усилия, близкие':'Courage, effort, siblings','Дом, мать, сердце, корни':'Home, mother, heart, roots','Творчество, дети, разум':'Creativity, children, mind','Здоровье, долги, служение':'Health, debts, service','Партнёр, союзы, договоры':'Partner, unions, contracts','Тайны, трансформация, наследие':'Secrets, transformation, legacy','Дхарма, учитель, удача, путь':'Dharma, teacher, fortune, path','Карьера, призвание, статус':'Career, vocation, status','Доходы, друзья, желания':'Income, friends, desires','Освобождение, затраты, чужбина':'Liberation, expenses, foreign lands',
/* === calc-systems === */
'🧭 Системы расчёта':'🧭 Calculation systems','Ведическое ядро остаётся. Каждая система добавляет грань Даймону.':'The Vedic core remains. Each system adds a facet to the Daimon.','Грани Даймона · доп. системы':'Daimon facets · extra systems','Грани Даймона':'Daimon facets','ॐ Ведическое ядро':'ॐ Vedic core','Сначала рассчитай натальную карту кнопкой выше.':'First calculate your natal chart with the button above.','Выбери систему выше, чтобы увидеть расчёт и добавить грань.':'Pick a system above to see the calculation and add a facet.','Пока только ведическое ядро. Добавь грани из систем выше.':'For now only the Vedic core. Add facets from the systems above.','Добавить грань Даймону':'Add facet to Daimon','Убрать грань':'Remove facet','Ядро остаётся ведическим (':'The core remains Vedic (','). Грани расширяют его голос.':'). Facets expand its voice.','Добавь грани на экране Натал → Системы расчёта.':'Add facets on the Natal screen → Calculation systems.','Сначала рассчитай карту':'First calculate the chart','Грань убрана':'Facet removed','✦ Грань добавлена Даймону':'✦ Facet added to the Daimon',
'Западная':'Western','Китайская':'Chinese','Майя':'Maya','Нумерология':'Numerology','Хьюман Дизайн':'Human Design','Круголет':'Krugolet',
'Тропический зодиак (как в западной астрологии): к сидерическим долготам добавлена аянамша ≈':'Tropical zodiac (as in Western astrology): ayanamsha added to sidereal longitudes ≈','Тропическая воля ':'Tropical will ','Солнце в ':'Sun in ',
'Крыса':'Rat','Бык':'Ox','Тигр':'Tiger','Кролик':'Rabbit','Дракон':'Dragon','Змея':'Snake','Лошадь':'Horse','Коза':'Goat','Обезьяна':'Monkey','Петух':'Rooster','Собака':'Dog','Свинья':'Pig',
'ум и запас':'wit and reserve','труд и опора':'work and support','смелость и натиск':'courage and drive','такт и мир':'tact and peace','мощь и удача':'might and luck','мудрость и интуиция':'wisdom and intuition','свобода и страсть':'freedom and passion','искусство и кротость':'art and gentleness','смекалка и игра':'cleverness and play','точность и честь':'precision and honor','верность и защита':'loyalty and protection','щедрость и покой':'generosity and peace',
'Дерево Ян':'Yang Wood','Дерево Инь':'Yin Wood','Огонь Ян':'Yang Fire','Огонь Инь':'Yin Fire','Земля Ян':'Yang Earth','Земля Инь':'Yin Earth','Металл Ян':'Yang Metal','Металл Инь':'Yin Metal','Вода Ян':'Yang Water','Вода Инь':'Yin Water','Дерево':'Wood','Металл':'Metal',
'Ба-Цзы по году ':'BaZi by year ',' (без поправки на китайский Новый год — приближённо).':' (without Chinese New Year correction — approximate).','Тотем года':'Year totem','Небесный ствол':'Heavenly stem','. Стихия ':'. The element ',' задаёт способ действия.':' sets the way of acting.',
'Имиш':'Imix','Ик':'Ik','Акбаль':'Akbal','Кан':'Kan','Чикчан':'Chicchan','Кими':'Cimi','Маник':'Manik','Ламат':'Lamat','Мулук':'Muluc','Ок':'Oc','Чуэн':'Chuen','Эб':'Eb','Бен':'Ben','Иш':'Ix','Мен':'Men','Киб':'Cib','Кабан':'Caban','Эцнаб':'Etznab','Кавак':'Cauac','Ахау':'Ahau',
'исток, доверие':'source, trust','ветер, дух и слово':'wind, spirit and word','ночь, интуиция':'night, intuition','семя, цель':'seed, purpose','змей, сила тела':'serpent, body power','переход, отпускание':'transition, letting go','рука, свершение':'hand, accomplishment','звезда, гармония':'star, harmony','луна, поток':'moon, flow','пёс, верность':'dog, loyalty','обезьяна, игра':'monkey, play','дорога судьбы':'road of destiny','тростник, авторитет':'reed, authority','ягуар, магия':'jaguar, magic','орёл, видение':'eagle, vision','воин, разум':'warrior, reason','земля, синхрония':'earth, synchrony','зеркало, ясность':'mirror, clarity','буря, преображение':'storm, transformation','солнце, просветление':'sun, enlightenment',
'Цолькин (корреляция GMT 584283) по дате рождения.':'Tzolkin (GMT 584283 correlation) by birth date.','Кин':'Kin','Тон':'Tone','Печать':'Seal',
'Лидер, воля, начало':'Leader, will, beginning','Дипломат, союз, чувство':'Diplomat, union, feeling','Творец, слово, радость':'Creator, word, joy','Строитель, порядок, труд':'Builder, order, work','Странник, свобода, перемены':'Wanderer, freedom, change','Хранитель, любовь, забота':'Keeper, love, care','Мудрец, поиск, тишина':'Sage, search, silence','Властелин, сила, изобилие':'Ruler, power, abundance','Гуманист, отдача, завершение':'Humanist, giving, completion','Вестник, интуиция, свет':'Herald, intuition, light','Мастер-строитель, замысел':'Master-builder, design','Учитель, служение-любовь':'Teacher, service-love',
'Число Жизненного Пути из даты ':'Life Path number from date ','Число судьбы':'Destiny number','Разбор Д·М·Г':'Breakdown D·M·Y','Число дня':'Day number','. Путь = ':'. Path = ','Путь ':'Path ','Число ':'Number ',
'Круголет Числобога (Коляды Дар) — народный календарь, приближённо. Лето ≈':'Krugolet of Chislobog (Kolyada Gift) — folk calendar, approximate. Year ≈','Тотем-год':'Year totem','Стихия лета':'Year element','Покровитель года — ':'Patron of the year — ',', стихия ':', element ','. Знаешь точный анкор-год — уточним соответствие.':'. If you know the exact anchor year, we will refine the match.',
'Тёмный Сох (Лось)':'Dark Sokh (Elk)','Жалящий Шершень':'Stinging Hornet','Притаившийся Лют (Волк)':'Lurking Lute (Wolf)','Огнегривый Конь':'Fire-maned Horse','Жемчужная Щука':'Pearl Pike','Бородатая Жаба':'Bearded Toad','Дикий Вепрь':'Wild Boar','Белый Филин':'White Owl','Шипящий Уж':'Hissing Grass Snake','Крадущийся Лис':'Sneaking Fox','Свернувшийся Ёж':'Curled Hedgehog','Парящий Орёл':'Soaring Eagle','Прядущий Мизгирь (Паук)':'Spinning Mizgir (Spider)','Кричащий Петух':'Crowing Rooster','Златорогий Тур':'Golden-horned Aurochs','Огненная Векша (Белка)':'Fiery Veksha (Squirrel)','Звезда':'Star','Небеса':'Heavens','Океан-Море':'Ocean-Sea','Бог':'God','Солнце':'Sun','стихия ':'element ',
/* === HD (bodygraph) === */
'Манифестирующий Генератор':'Manifesting Generator','Манифестор':'Manifestor','Генератор':'Generator','Проектор':'Projector','Рефлектор':'Reflector',
'Откликаться — ждать сакрального отклика':'Respond — wait for the sacral response','Откликаться, затем информировать':'Respond, then inform','Информировать перед действием':'Inform before acting','Ждать приглашения и признания':'Wait for invitation and recognition','Ждать полный лунный цикл (~28 дней)':'Wait a full lunar cycle (~28 days)',
'Эмоциональный (Солнечное сплетение) — ясность приходит со временем, через волну; не решать на пике':'Emotional (Solar Plexus) — clarity comes over time, through the wave; do not decide at the peak','Сакральный — мгновенный отклик тела (звук «угу/не-а») здесь и сейчас':'Sacral — instant body response (a sound) here and now','Селезёночный — тихая мгновенная интуиция, говорит один раз':'Splenic — quiet instant intuition, speaks once','Эго (Сердце) — что по-настоящему хочешь и что выгодно воле':'Ego (Heart) — what you truly want and what serves the will','Само-проецируемый (G) — слышать собственный голос в разговоре с доверенными':'Self-projected (G) — hear your own voice in talk with trusted ones','Лунный — решение вызревает полный цикл ~28 дней':'Lunar — the decision ripens over a full ~28-day cycle','Ментальный/средовой — проговаривать в верном окружении, без внутреннего авторитета':'Mental/environmental — talk it through in the right environment, with no inner authority',
'Эмоциональный':'Emotional','Сакральный':'Sacral','Селезёночный':'Splenic','Эго':'Ego','Само-проецируемый':'Self-projected','Лунный':'Lunar','Ментальный':'Mental',
'Исследователь / Мученик':'Investigator / Martyr','Исследователь / Оппортунист':'Investigator / Opportunist','Отшельник / Оппортунист':'Hermit / Opportunist','Отшельник / Еретик':'Hermit / Heretic','Мученик / Еретик':'Martyr / Heretic','Мученик / Ролевая модель':'Martyr / Role Model','Оппортунист / Ролевая модель':'Opportunist / Role Model','Оппортунист / Исследователь':'Opportunist / Investigator','Еретик / Исследователь':'Heretic / Investigator','Еретик / Отшельник':'Heretic / Hermit','Ролевая модель / Отшельник':'Role Model / Hermit','Ролевая модель / Мученик':'Role Model / Martyr',
'Голова (Корона)':'Head (Crown)','Аджна':'Ajna','Горло':'Throat','G-центр (Самость)':'G-center (Self)','Сердце (Эго)':'Heart (Ego)','Селезёнка':'Spleen','Сакрал':'Sacral','Солнечное сплетение':'Solar Plexus','Корень':'Root',
'Вдохновение':'Inspiration','Биение':'The Beat','Мутация':'Mutation','Логика':'Logic','Ритм':'Rhythm','Близость':'Intimacy','Альфа':'Alpha','Концентрация':'Concentration','Пробуждение':'Awakening','Следование себе':'Following the self','Совершенная форма':'Perfected form','Любопытство':'Curiosity','Открытость':'Openness','Прозелит':'The Prodigal','Талант':'Talent','Принятие':'Acceptance','Суждение':'Judgment','Синтез':'Synthesis','Харизма':'Charisma','Мозговая волна':'Brain wave','Деньги':'Money','Структурирование':'Structuring','Осознание':'Awareness','Инициация':'Initiation','Капитуляция':'Surrender','Опека':'Preservation','Упрямство':'Struggle','Преуспевание':'Discovery','Признание':'Recognition','Преображение':'Transformation','Власть':'Power','Непостоянство':'Transitoriness','Сообщество':'Community','Настроение':'Moods','Зрелость':'Maturation','Абстракция':'Abstinence',
'Тип':'Type','Стратегия':'Strategy','Авторитет':'Authority','Профиль':'Profile','Определение':'Definition','Каналы':'Channels','Крест воплощения':'Incarnation cross','9 центров':'9 centers','Активации':'Activations','Дизайн':'Design','Личность (Ворота.Линия)':'Personality (Gate.Line)','определён':'defined','открыт':'open','Стратегия и Авторитет — твой компас принятия решений: ':'Strategy and Authority are your decision compass: ','Нет (открытая)':'No (open)','Единая (Single)':'Unified (Single)','Раздельная (Split)':'Split','Тройная раздельная':'Triple split','Четверная раздельная':'Quadruple split',
/* === прочие подписи экранов === */
'Стихия лета':'Year element','Стихия':'Element','Качества из карты':'Qualities from the chart'
};

/* --- движок замены --- */
var CYR=/[\u0400-\u04FF]/;
var SKIP={aiChat:1,aiInput:1,journalFeed:1,dayText:1,newIntent:1,mSearch:1,bDate:1,bTime:1,bCity:1,bLat:1,bLon:1,bTz:1};
var RE=null;
function esc(s){return s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');}
function buildRE(){var keys=Object.keys(T).sort(function(a,b){return b.length-a.length;});RE=new RegExp(keys.map(esc).join('|'),'g');}
function tr(s){return s.replace(RE,function(m){return T[m]!=null?T[m]:m;});}

function isEn(){try{return window.AwaraI18n&&window.AwaraI18n.lang==='en';}catch(e){return false;}}

var OBS=null,scheduled=false;
function skip(n){var p=n.parentNode;while(p&&p.nodeType===1){var tn=p.nodeName;if(tn==='SCRIPT'||tn==='STYLE'||tn==='TEXTAREA'||tn==='INPUT'||p.isContentEditable)return true;if(p.id&&SKIP[p.id])return true;p=p.parentNode;}return false;}
function localize(root){
 if(!root||!RE)return;
 var w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,null,false);
 var nodes=[],x;
 while(x=w.nextNode()){if(x.nodeValue&&CYR.test(x.nodeValue)&&!skip(x))nodes.push(x);}
 for(var i=0;i<nodes.length;i++){var v=nodes[i].nodeValue,nv=tr(v);if(nv!==v)nodes[i].nodeValue=nv;}
}
function connectObs(){var ph=document.querySelector('.phone')||document.body;if(ph&&OBS)OBS.observe(ph,{childList:true,subtree:true,characterData:true});}
function pass(){
 if(!isEn())return;
 if(OBS)OBS.disconnect();
 try{var ph=document.querySelector('.phone')||document.body;localize(ph);}catch(e){}
 connectObs();
}
function rerender(){
 var fns=['renderNatal','renderDaimon','renderIstok','renderResult','renderYear','renderGame','updateLight','renderIntents','renderJournal','renderPatron'];
 for(var i=0;i<fns.length;i++){try{if(typeof window[fns[i]]==='function')window[fns[i]]();}catch(e){}}
 var mods=[['AwaraNatalDeep','enhance'],['AwaraNatalDeep','render'],['AwaraCalc','render'],['AwaraAgents','update'],['AwaraAgents','render'],['AwaraForms','refresh'],['AwaraForms','render'],['AwaraPatron','render']];
 for(var j=0;j<mods.length;j++){try{var o=window[mods[j][0]];if(o&&typeof o[mods[j][1]]==='function')o[mods[j][1]]();}catch(e){}}
}
function onLang(){setTimeout(function(){try{rerender();}catch(e){}setTimeout(pass,50);},20);}
function schedule(){if(scheduled)return;scheduled=true;var raf=window.requestAnimationFrame||function(f){return setTimeout(f,16);};raf(function(){scheduled=false;pass();});}
function boot(){
 buildRE();
 OBS=new MutationObserver(function(){if(isEn())schedule();});
 connectObs();
 window.addEventListener('awara:lang',onLang);
 [120,400,900,1800,3000].forEach(function(d){setTimeout(pass,d);});
}
function extend(o){try{for(var k in o){if(Object.prototype.hasOwnProperty.call(o,k))T[k]=o[k];}buildRE();}catch(e){}try{if(isEn()){rerender();setTimeout(pass,30);}}catch(e){}}
window.AwaraI18nDeep={__ready:true,pass:pass,tr:tr,T:T,rerender:rerender,extend:extend};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
