/* i18n-deep6 v1: artifact generators (gMyth/gSteps/gArtifact/gTrack/gAyur/gCover/gAdvice) + nakshatra lore.
   SELF-CONTAINED substring replacement; does NOT touch the shared engine. */
(function(){
'use strict';
var PAIRS=[
['Овен',"Aries"],['Телец',"Taurus"],['Близнецы',"Gemini"],['Рак',"Cancer"],['Лев',"Leo"],['Дева',"Virgo"],['Весы',"Libra"],['Скорпион',"Scorpio"],['Стрелец',"Sagittarius"],['Козерог',"Capricorn"],['Водолей',"Aquarius"],['Рыбы',"Pisces"],
['Огонь',"Fire"],['Земля',"Earth"],['Воздух',"Air"],['Вода',"Water"],['Эфир',"Ether"],['Гроза',"Storm"],['Рассвет',"Dawn"],
['огонь',"fire"],['земля',"earth"],['воздух',"air"],['вода',"water"],['эфир',"ether"],
['Капха-Вата',"Kapha-Vata"],['Питта',"Pitta"],['Капха',"Kapha"],['Вата',"Vata"],
['В час, когда Лагна взошла в ',"At the hour when the Ascendant rose in "],[', а Солнце горело в ',", and the Sun blazed in "],[', пробудился тот, чью Луну держит накшатра ',", awoke the one whose Moon is held by the nakshatra "],['. Её божество — ',". Its deity is "],[', знак — ',", its symbol — "],[', и шакти её: «',", and its shakti: «"],
['Спутник по имени ',"A companion named "],[' идёт стихией '," walks with the element "],['Сейчас доверие между вами — ',"Right now the trust between you is "],['Безымянный',"Nameless"],
['Сегодня герой смотрит сквозь ',"Today the hero looks through "],[' линз: '," lenses: "],['. Их голоса сплетаются в один наказ:',". Their voices weave into a single charge:"],
['Уровень Света дня — ',"The day's Light level is "],['Миф разворачивается в полную силу: дорога открыта на семь ступеней.',"The myth unfolds in full force: the road opens to seven stages."],['Света достаточно, чтобы миф зазвучал и повёл дальше.',"There is enough Light for the myth to sound and lead onward."],['Свет ещё тускл — герою предстоит раздуть искру, прежде чем миф окрепнет.',"The Light is still dim — the hero must fan the spark before the myth grows strong."],['Миф дня',"Myth of the Day"],['Накшатра ',"Nakshatra "],
['Открыто ступеней: ',"Stages unlocked: "],[' из 7 (по уровню Света '," of 7 (by Light level "],['— закрыто, нужно больше Света',"— locked, more Light needed"],['7 ступеней',"7 Stages"],['Алхимический путь дня',"The day's alchemical path"],
['Кальцинация',"Calcination"],['Растворение',"Dissolution"],['Разделение',"Separation"],['Соединение',"Conjunction"],['Гниение',"Putrefaction"],['Возгонка',"Sublimation"],['Коагуляция',"Coagulation"],
['сжечь лишнее в огне ',"burn away the excess in the fire of "],['Отпустить форму, как учит ',"Release the form, as taught by "],['Отделить своё от чужого',"Separate what is yours from what is not"],['Сплавить ',"Fuse "],[' и волю'," and will"],['Дать старому достойно умереть',"Let the old die with dignity"],['Поднять суть к свету',"Raise the essence toward the light"],['Закрепить камень дня',"Fix the stone of the day"],
['вулканическое стекло',"volcanic glass"],['тёмный нефрит',"dark jade"],['звонкая бронза',"ringing bronze"],['лунный перламутр',"lunar mother-of-pearl"],
['Реликвия',"Relic"],['Заряженный',"Charged"],['Зачаток',"Seed"],
['Класс',"Class"],['Свойства',"Properties"],['Материал: ',"Material: "],[' (стихия '," (element "],['Сила: «',"Power: «"],['» — от накшатры ',"» — from the nakshatra "],['Хранитель: ',"Guardian: "],['Гравировка линз: ',"Lens engraving: "],['Заряд Света: ',"Light charge: "],['Артефакт',"Artifact"],
['восходящий, кульминационный',"ascending, climactic"],['медитативно-движущийся',"meditative, flowing"],['тёмный, собирающий',"dark, gathering"],['таблы, перкуссия, дисторшн-дрон',"tabla, percussion, distortion drone"],['ханг, контрабас, варган',"hang drum, double bass, jaw harp"],['бансури, арп-синт, шейкеры',"bansuri, arp synth, shakers"],['виолончель, дроны, капли воды',"cello, drones, water drops"],['Параметры',"Parameters"],['Тональность: ',"Key: "],['Настроение: ',"Mood: "],['Инструменты: ',"Instruments: "],['Название',"Title"],[' · день '," · day "],['Трек',"Track"],
['охлаждать: кокос, мята, прохладные практики, меньше острого',"cool down: coconut, mint, cooling practices, less spice"],['заземлять: тёплая еда, масло, режим, медленное дыхание',"ground yourself: warm food, oil, routine, slow breathing"],['разгонять: специи, движение, лёгкость, ранний подъём',"energize: spices, movement, lightness, early rising"],['Доша Лагны',"Ascendant Dosha"],['Баланс стихий',"Elemental balance"],['Рекомендация дня',"Recommendation of the day"],['Аюрведа',"Ayurveda"],
['багрянец, золото, чёрный обсидиан',"crimson, gold, black obsidian"],['охра, тёмная зелень, бронза',"ochre, dark green, bronze"],['индиго, серебро, белый',"indigo, silver, white"],['глубокий синий, перламутр, фиолет',"deep blue, mother-of-pearl, violet"],['герой в центре, нимб из семи колец, восходящий свет',"a hero at the center, a halo of seven rings, ascending light"],['фигура в три четверти, спираль матриц вокруг',"a three-quarter figure, a spiral of matrices around"],['силуэт во тьме, одна искра в груди',"a silhouette in darkness, a single spark in the chest"],['Композиция',"Composition"],['Палитра',"Palette"],['Символы',"Symbols"],['Знак Лагны: ',"Ascendant sign: "],['Символ накшатры: ',"Nakshatra symbol: "],['Даймон: ',"Daimon: "],['Линзы: ',"Lenses: "],['Обложка',"Cover"],
['Переплавь день в Тигле, чтобы получить совет.',"Melt the day in the Crucible to receive advice."],['Голоса линз',"Voices of the lenses"],['Совет дня уже выдан: ',"The day's advice has already been given: "],['Совет+',"Advice+"],['Совет',"Advice"],['Миф',"Myth"],['Дроп Притхви',"Prithvi Drop"],['линзы не выбраны',"no lenses selected"],['без линз',"no lenses"],
['Ашвини',"Ashwini"],['Бхарани',"Bharani"],['Криттика',"Krittika"],['Рохини',"Rohini"],['Мригашира',"Mrigashira"],['Ардра',"Ardra"],['Пунарвасу',"Punarvasu"],['Пушья',"Pushya"],['Ашлеша',"Ashlesha"],['Магха',"Magha"],['Пурва-Пхальгуни',"Purva Phalguni"],['Уттара-Пхальгуни',"Uttara Phalguni"],['Хаста',"Hasta"],['Читра',"Chitra"],['Свати',"Swati"],['Вишакха',"Vishakha"],['Анурадха',"Anuradha"],['Джьештха',"Jyeshtha"],['Мула',"Mula"],['Пурва-Ашадха',"Purva Ashadha"],['Уттара-Ашадха',"Uttara Ashadha"],['Шравана',"Shravana"],['Дхаништха',"Dhanishtha"],['Шатабхиша',"Shatabhisha"],['Пурва-Бхадрапада',"Purva Bhadrapada"],['Уттара-Бхадрапада',"Uttara Bhadrapada"],['Ревати',"Revati"],
['Ашвины-целители',"the Ashvin healers"],['Яма',"Yama"],['Агни',"Agni"],['Брахма',"Brahma"],['Сома',"Soma"],['Рудра',"Rudra"],['Адити',"Aditi"],['Брихаспати',"Brihaspati"],['Наги',"the Nagas"],['Питри-предки',"the Pitri ancestors"],['Бхага',"Bhaga"],['Арьяман',"Aryaman"],['Савитар',"Savitar"],['Тваштар',"Tvashtar"],['Ваю',"Vayu"],['Индра-Агни',"Indra-Agni"],['Митра',"Mitra"],['Индра',"Indra"],['Ниррити',"Nirriti"],['Апас',"Apas"],['Вишведевы',"the Vishvedevas"],['Вишну',"Vishnu"],['Васу',"the Vasus"],['Варуна',"Varuna"],['Аджа Экапада',"Aja Ekapada"],['Ахир Будхнья',"Ahir Budhnya"],['Пушан',"Pushan"],
['голова коня',"a horse's head"],['лезвие пламени',"a blade of flame"],['голова оленя',"a deer's head"],['капля-слеза',"a teardrop"],['колчан стрел',"a quiver of arrows"],['вымя коровы',"a cow's udder"],['свернувшаяся змея',"a coiled serpent"],['ложе (перед)',"a bed (front)"],['ложе (тыл)',"a bed (back)"],['побег на ветру',"a shoot in the wind"],['арка триумфа',"an arch of triumph"],['зонт старейшины',"an elder's umbrella"],['связка корней',"a bundle of roots"],['бивень слона',"an elephant tusk"],['три следа',"three footprints"],['круг ста целителей',"a circle of a hundred healers"],['огненный столп',"a pillar of fire"],['змей глубин',"a serpent of the deep"],['колесница',"a chariot"],['жемчужина',"a pearl"],['ладонь',"a palm"],['лотос',"a lotus"],['барабан',"a drum"],['трон',"a throne"],['йони',"a yoni"],['веер',"a fan"],['рыба',"a fish"],
['исцелять стремительно',"to heal swiftly"],['нести и преображать',"to carry and transform"],['сжигать лишнее',"to burn away the excess"],['растить изобилие',"to grow abundance"],['искать суть',"to seek the essence"],['усилие сквозь бурю',"effort through the storm"],['возвращаться обновлённым',"to return renewed"],['питать и защищать',"to nourish and protect"],['обвивать мудростью',"to entwine with wisdom"],['держать власть рода',"to hold the power of the lineage"],['дарить наслаждение',"to bestow delight"],['скреплять союзы',"to bind alliances"],['мастерить руками',"to craft with the hands"],['творить форму',"to create form"],['быть независимым',"to be independent"],['достигать цели',"to reach the goal"],['хранить дружбу',"to keep friendship"],['нести старшинство',"to bear seniority"],['рвать до корня',"to tear out to the root"],['быть непобедимым',"to be invincible"],['одержать окончательную победу',"to win the final victory"],['слушать и связывать',"to listen and connect"],['задавать ритм',"to set the rhythm"],['исцелять тайно',"to heal in secret"],['гореть аскезой',"to burn with asceticism"],['хранить глубинный покой',"to keep deep peace"],['питать путь до конца',"to nourish the path to its end"]
];
PAIRS.sort(function(a,b){return b[0].length-a[0].length;});
var CYR=/[\u0400-\u04FF]/;
function isEn(){try{return window.AwaraI18n&&window.AwaraI18n.lang==='en';}catch(e){return false;}}
function tr(s){for(var i=0;i<PAIRS.length;i++){var k=PAIRS[i][0];if(s.indexOf(k)>=0)s=s.split(k).join(PAIRS[i][1]);}return s;}
function pass(){if(!isEn())return;try{var root=document.querySelector('.phone')||document.body;if(!root)return;var w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,null,false),x,ns=[];while(x=w.nextNode())ns.push(x);for(var i=0;i<ns.length;i++){var v=ns[i].nodeValue;if(!v||!CYR.test(v))continue;var nv=tr(v);if(nv!==v)ns[i].nodeValue=nv;}}catch(e){}}
var sched=false;
function schedule(){if(sched)return;sched=true;var raf=window.requestAnimationFrame||function(f){return setTimeout(f,16);};raf(function(){sched=false;pass();});}
function boot(){try{var ph=document.querySelector('.phone')||document.body;var obs=new MutationObserver(function(){if(isEn())schedule();});if(ph)obs.observe(ph,{childList:true,subtree:true,characterData:true});}catch(e){}
window.addEventListener('awara:lang',function(){setTimeout(pass,60);setTimeout(pass,280);});
[250,700,1400,2400,3600].forEach(function(d){setTimeout(pass,d);});
window.AwaraI18nDeep6={__ready:true,PAIRS:PAIRS,pass:pass};}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
